---
application:
  name: "demo-deploy-qovery"
  project: "first-frontity-demo"
  organization: "QoveryCommunity"
routers:
- name: "main-demo-deploy-qovery"
  routes:
  - application_name: "demo-deploy-qovery"
    paths:
    - "/*"
